FORMAT: 1A
HOST: http://http://10.180.217.69:8080/

# AddressValMicroservices

Address Validation Microservices is a simple API allowing consumers to validate their address format.

## Questions Collection [/address/addressval]

### List All Requests [GET]
+ Request (application/json)

    + Attributes
        + name (string, required) - Customer Name
        + email (string, required) - Customer Email
        + phone (string, required) - Customer Phone
        + address (string, required) - Customer Address
        + city (string, required) - City
        + zipcode (string, required) - ZIPCODE of city

   
+ Response 200 (application/json)

[
 {
              "name": "Neo Joy",
              "email": "sen@rediff.com",
               "phone": +44444444",
              "address": "Greams Road",
               "city": Chennai",
              "zipcode": "609001"
            }
            
 + Response 201 (application/json)

        {
            "notification": "You have successfully created, pending their confirmation(s).",
            "success": true
        }
        
+ Response 400 (application/json)

        {
            "errors": "You don't have the appropriate rights to create request",
            "success": false
        }

]


### Create a New  Request [POST]

+ Request (application/json)

    + Attributes
        + name (string, required) - Customer Name
        + email (string, required) - Customer Email
        + phone (string, required) - Customer Phone
        + address (string, required) - Customer Address
        + city (string, required) - City
        + zipcode (string, required) - ZIPCODE of city

   
+ Response 200 (application/json)

[
 {
              "name": "Neo Joy",
              "email": "sen@rediff.com",
               "phone": +44444444",
              "address": "Greams Road",
               "city": Chennai",
              "zipcode": "609001"
            }
            
 + Response 201 (application/json)

        {
            "notification": "You have successfully created, pending their confirmation(s).",
            "success": true
        }
        
+ Response 400 (application/json)

        {
            "errors": "You don't have the appropriate rights to create request",
            "success": false
        }

]

            }