FORMAT: 1A
# AddressValMicroservices

Addressvalidation Microservice to add,delete,update records.

# Description Of Usual Server Responses:

- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 401 `Unauthorized` - authentication failed or user doesn't have permissions for requested operation.
- 403 `Forbidden` - access denied.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.


**address attributes:**

- id `(Number)` : unique identifier. 
- name `(String)` : First Name.
- email `(String)` : Last Name.
- phone `(String)` : email id of the user.
- address `(String)` : First Name.
- city `(String)` : Last Name.
- zipcode `(String)` : email id of the user.

---
## address Collection [/address/addressval({name},{email},{phone},{address},{city},{zipcode})]

### List all address [GET]

Retrieve paginated list of users.

+ Parameters
    + name: Senthil (string, required)
    + email: John@gmail.com (string, required)
    + phone: 9999999 (string, required)
    + address: Raymond Street (string, required)
    + zipcode: Zipcode (string, required)
    + city: Chennai (string, required)
    
 

+ Response 200 (application/json)

        [
            {
                "name": "RAJA",
                "email": "pandurang@email.com",
                "phone": "888888888"
                "address": "RAJA",
                "zipcode": "609001",
                "city": "Chennai"
            }
        ]

+ Response 401 (application/json)

        {
            "error": "error.unauthorized"
        }


## User [/users/{id}]
A single User object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the User to perform action with.

### Retrieve a address [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "id": 1,
                 "name": "RAJA",
                "email": "pandurang@email.com",
                "phone": "888888888"
                "address": "RAJA",
                "zipcode": "609001",
                "city": "Chennai"
            }
            
+ Response 401 (application/json)

        {
            "error": "error.unauthorized"
        }

### Update a address [POST]
Update address details
+ Request (application/json)

       {
                "id": 2,
                 "name": "JOHN",
                "email": "john@email.com",
                "phone": "888888888"
                "address": "Cathedral road",
                "zipcode": "600001",
                "city": "Chennai"
            }

+ Response 200 (application/json)

        {
                "id": 2,
                 "name": "JOHN",
                "email": "john@email.com",
                "phone": "888888888"
                "address": "Cathedral road",
                "zipcode": "600001",
                "city": "Chennai"
            }
+ Response 401 (application/json)

        {
            "error": "error.unauthorized"
        }